# Generated by Django 4.2.9 on 2024-01-19 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_savingsdeposit"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="saving_goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.savinggoal",
            ),
        ),
    ]
